name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:
  
defaults:
  run:
    shell: pwsh

jobs:
  automerge:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
          use-github-auto-merge: true

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }} with caching
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - run: npm ci
    - run: npm run build

    - name: Check formatting
      run: npm run lint
    # - run: npm test
    
